Adding broker endpoints
tiagosiebler/okx-api pull request #44
Opened 2024-01-27 16:39 UTC by jjmiranda

## Summary
Adding delete and Create API Keys for subAccounts

## Additional Information
Using the sema nomenclature and stardards for this repo and OKX documentation.

2024-01-29 11:18 UTC, tiagosiebler requested changes
Thank you for the PR! Small naming nitpick for the create api key fn. Could you also please revert the change to the package-lock.json? You can copy paste the one from the master branch, if you're not sure how to undo it. Thanks.

2024-01-29 11:18 UTC, tiagosiebler commented on src/rest-client.ts
> +  createAnAPIKeyForASubAccount (params: {
```suggestion
  createSubAccountAPIKey(params: {
```

2024-01-29 11:19 UTC, tiagosiebler commented
Please also increase the version number in the "package.json" file - it'll make the release process easier.

2024-01-29 22:07 UTC, jjmiranda commented
Ready!

2024-01-30 17:38 UTC, tiagosiebler commented on package.json
> +  "version": "1.2.3",
```suggestion
  "version": "1.2.1",
```

2024-01-30 17:39 UTC, merged